cargohold:
  host: 0.0.0.0
  port: 8084

aws:
  keyId: dummy
  secretKey: dummy
  s3Bucket: dummy-bucket
  s3Endpoint: http://localhost:4570 # https://s3-eu-west-1.amazonaws.com:443

settings:
  maxTotalBytes: 27262976
  downloadLinkTTL: 300    # Seconds
